---

- name: Create jenkins container
  community.docker.docker_container:
    name: jenkins
    image: {{jenkins_image}}
    ports:
    - 80:8080
    - 50000:50000
    volumes:
    - jenkins_home:/var/jenkins_home